apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-scheduler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: gitlab-kubernetes-laravel-cred
          containers:
          - name: scheduler
            image: registry.gitlab.com/devops0077/kubernetes-laravel/php-cli:0.0.1
            imagePullPolicy: Always
            command:
            - php
            args:
            - artisan
            - schedule:run
            envFrom:
            - secretRef:
                name: php-secret
            - configMapRef:
                name: php-configmap
          restartPolicy: OnFailure
