apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      imagePullSecrets:
      - name: gitlab-k8s-laravel-cred
      containers:
        - name: nginx
          image: registry.gitlab.com/devops0077/k8s-laravel/nginx:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: FPM_HOST
            value: php-fpm-svc:9000
