apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    tier: frontend
spec:
  type: NodePort
  selector:
    app: nginx
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      # targetPort: 80
