apiVersion: v1
kind: Secret
metadata:
  name: php-secret
type: Opaque
stringData:
  APP_KEY: "base64:wQCfI6w85gq7BG1Yt8Ts1MGq0tXNP74LsQy2xUkxJtI="
  DB_USERNAME: "thomas"
  DB_PASSWORD: "secret"
  REDIS_PASSWORD: "a-very-complex-password-here"
  MAIL_PASSWORD: "null"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
