apiVersion: v1
kind: Service
metadata:
  name: php-fpm-svc
  labels:
    app: php-fpm
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: php-fpm
    tier: backend
  ports:
    - name: fpm-port
      protocol: TCP
      port: 9000
      targetPort: 9000
