apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv
spec:
  storageClassName: local-storage-mysql
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql/
  # local:
  #   path: /mnt/data/mysql
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - minikube
