apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-mysql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer # delay volume binding until Pod scheduling
allowVolumeExpansion: false
reclaimPolicy: Delete
