apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv1
spec:
  storageClassName: local-storage-redis
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis1/
  # local:
  #   path: /mnt/data/redis1
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - minikube

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv2
spec:
  storageClassName: local-storage-redis
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis2/
  # local:
  #   path: /mnt/data/redis2
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - minikube

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv3
spec:
  storageClassName: local-storage-redis
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis3/
  # local:
  #   path: /mnt/data/redis3
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - minikube
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv4
spec:
  storageClassName: local-storage-redis
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis4/
  # local:
  #   path: /mnt/data/redis3
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - minikube
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv5
spec:
  storageClassName: local-storage-redis
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis5/
  # local:
  #   path: /mnt/data/redis3
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - minikube
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-local-pv6
spec:
  storageClassName: local-storage-redis
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis6/
  # local:
  #   path: /mnt/data/redis3
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - minikube
